-- MySQL Script generated by MySQL Workbench
-- Fri Jun  4 10:58:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controleVacinacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controleVacinacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controleVacinacao` DEFAULT CHARACTER SET utf8 ;
USE `controleVacinacao` ;

-- -----------------------------------------------------
-- Table `controleVacinacao`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleVacinacao`.`Endereco` (
  `id` INT AUTO_INCREMENT NOT NULL ,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleVacinacao`.`Vacinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleVacinacao`.`Vacinador` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vacinador_Endereco1_idx` (`Endereco_id` ASC) ,
  CONSTRAINT `fk_Vacinador_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `controleVacinacao`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleVacinacao`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleVacinacao`.`Paciente` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `fatorRisco` VARCHAR(45) NOT NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Paciente_Endereco1_idx` (`Endereco_id` ASC) ,
  CONSTRAINT `fk_Paciente_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `controleVacinacao`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleVacinacao`.`Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleVacinacao`.`Vacina` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `lote` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleVacinacao`.`Posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleVacinacao`.`Posto` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Posto_Vacinacao_Endereco1_idx` (`Endereco_id` ASC) ,
  CONSTRAINT `fk_Posto_Vacinacao_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `controleVacinacao`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleVacinacao`.`AplicacaoVacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleVacinacao`.`AplicacaoVacina` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `dose` VARCHAR(45) NOT NULL,
  `Vacina_id` INT NOT NULL,
  `Paciente_id` INT NOT NULL,
  `Vacinador_id` INT NOT NULL,
  `Posto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_AplicacaoVacina_Vacina_idx` (`Vacina_id` ASC) ,
  INDEX `fk_AplicacaoVacina_Paciente1_idx` (`Paciente_id` ASC) ,
  INDEX `fk_AplicacaoVacina_Vacinador1_idx` (`Vacinador_id` ASC) ,
  INDEX `fk_AplicacaoVacina_Posto1_idx` (`Posto_id` ASC) ,
  CONSTRAINT `fk_AplicacaoVacina_Vacina`
    FOREIGN KEY (`Vacina_id`)
    REFERENCES `controleVacinacao`.`Vacina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AplicacaoVacina_Paciente1`
    FOREIGN KEY (`Paciente_id`)
    REFERENCES `controleVacinacao`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AplicacaoVacina_Vacinador1`
    FOREIGN KEY (`Vacinador_id`)
    REFERENCES `controleVacinacao`.`Vacinador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AplicacaoVacina_Posto1`
    FOREIGN KEY (`Posto_id`)
    REFERENCES `controleVacinacao`.`Posto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
